CREATE TABLE "Iron Man" (info text);
CREATE TABLE "Captain America" (info text);
CREATE TABLE "Thor" (info text);
CREATE TABLE "Bruce Banner" (info text);
CREATE TABLE "Hawkeye" (info text);
CREATE TABLE "Doctor Strange" (info text);
CREATE TABLE "Vision" (info text);
CREATE TABLE "Scarlet Witch" (info text);
CREATE TABLE "Falcon" (info text);
CREATE TABLE "War Machine" (info text);
CREATE TABLE "Ant-Man" (info text);
CREATE TABLE "Bucky Barnes" (info text);
CREATE TABLE "The Wasp" (info text);
CREATE TABLE "Gamora" (info text);
CREATE TABLE "Spider-Man" (info text);
CREATE TABLE "Black Panther" (info text);
CREATE TABLE "Captain Marvel" (info text);

CREATE FUNCTION go_to_work() RETURNS void LANGUAGE 'sql' AS 'SELECT pg_sleep(100000)';
CREATE FUNCTION eat_dinner() RETURNS void LANGUAGE 'sql' AS 'SELECT pg_sleep(100000)';
CREATE FUNCTION go_to_school() RETURNS void LANGUAGE 'sql' AS 'SELECT pg_sleep(100000)';
CREATE FUNCTION pair() RETURNS void LANGUAGE 'sql' AS 'SELECT pg_sleep(100000)';
CREATE FUNCTION get_acquired() RETURNS void LANGUAGE 'sql' AS 'SELECT pg_sleep(100000)';
CREATE FUNCTION celebrate_ipo() RETURNS void LANGUAGE 'sql' AS 'SELECT pg_sleep(100000)';
CREATE FUNCTION travel_to_antartica() RETURNS void LANGUAGE 'sql' AS 'SELECT pg_sleep(100000)';
CREATE FUNCTION hide_from_earthquake() RETURNS void LANGUAGE 'sql' AS 'SELECT pg_sleep(100000)';
CREATE FUNCTION put_out_fire() RETURNS void LANGUAGE 'sql' AS 'SELECT pg_sleep(100000)';
CREATE FUNCTION turn_off_power() RETURNS void LANGUAGE 'sql' AS 'SELECT pg_sleep(100000)';
CREATE FUNCTION go_to_mars() RETURNS void LANGUAGE 'sql' AS 'SELECT pg_sleep(100000)';
CREATE FUNCTION sneeze() RETURNS void LANGUAGE 'sql' AS 'SELECT pg_sleep(100000)';
CREATE FUNCTION shower() RETURNS void LANGUAGE 'sql' AS 'SELECT pg_sleep(100000)';
CREATE FUNCTION ride_bart() RETURNS void LANGUAGE 'sql' AS 'SELECT pg_sleep(100000)';
CREATE FUNCTION commute() RETURNS void LANGUAGE 'sql' AS 'SELECT pg_sleep(100000)';
CREATE FUNCTION make_candy() RETURNS void LANGUAGE 'sql' AS 'SELECT pg_sleep(100000)';
CREATE FUNCTION play_tennis() RETURNS void LANGUAGE 'sql' AS 'SELECT pg_sleep(100000)';
CREATE FUNCTION play_guitar() RETURNS void LANGUAGE 'sql' AS 'SELECT pg_sleep(100000)';
CREATE FUNCTION run_a_marathon() RETURNS void LANGUAGE 'sql' AS 'SELECT pg_sleep(100000)';
CREATE FUNCTION take_over_the_world() RETURNS void LANGUAGE 'sql' AS 'SELECT pg_sleep(100000)';
